In [4]:
import pandas as pd

mat = pd.read_excel(r"C:\Users\DELL\OneDrive\Desktop\data\mat.xlsx")
por = pd.read_excel(r"C:\Users\DELL\OneDrive\Desktop\data\por.xlsx")

# نضيف عمود يحدد المادة
mat["subject"] = "math"
por["subject"] = "portuguese"

# ندمج
df = pd.concat([mat, por], ignore_index=True)

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,subject
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,math
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,math
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,math
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,math
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,math

In [6]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
subject       0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["avg_grade"] = ((df["G1"] + df["G2"] + df["G3"]) / 3).round(2)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,subject,avg_grade
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,math,5.67
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,math,5.33
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,math,8.33
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,math,14.67
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,math,8.67

In [9]:
df["status"] = df["G3"].apply(lambda x: "Pass" if x >= 10 else "Fail")
def level(x):
    if x >= 15:
        return "Excellent"
    elif x >= 12:
        return "Good"
    elif x >= 10:
        return "Pass"
    else:
        return "Fail"

df["level"] = df["G3"].apply(level)
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,Walc,health,absences,G1,G2,G3,subject,avg_grade,status,level
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,1,3,6,5,6,6,math,5.67,Fail,Fail
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,1,3,4,5,5,6,math,5.33,Fail,Fail
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,3,10,7,8,10,math,8.33,Pass,Pass
3,GP,F,15,U,GT3,T,4,2,health,services,...,1,5,2,15,14,15,math,14.67,Pass,Excellent
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,5,4,6,10,10,math,8.67,Pass,Pass

In [10]:
df = df.rename(columns={
    "sex":"gender",
    "famsize":"family_size",
    "Pstatus":"parent_status",
    "Medu": "mother_education",
    "Fedu": "father_education",
    "Mjob":"mother_job",
    "Fjob":"father_job",
    "traveltime":"travel_time",
    "studytime":"study_time",
    "schoolsup":"school_support",
    "famsup":"family_support",
    "higher":"wants_higher_education",
    "famrel":"family_relationship_quality",
    "goout":"go_out",
    "G1": "first_grade",
    "G2": "second_grade",
    "G3": "final_grade",
    "absences": "absence_days"
})

In [11]:
df = df.rename(columns={
    "parent_status":"parents_status"
})

In [12]:
df = df.drop(columns=["Walc", "Dalc"])

In [13]:
df.columns

Index(['school', 'gender', 'age', 'address', 'family_size', 'parents_status',
       'mother_education', 'father_education', 'mother_job', 'father_job',
       'reason', 'guardian', 'travel_time', 'study_time', 'failures',
       'school_support', 'family_support', 'paid', 'activities', 'nursery',
       'wants_higher_education', 'internet', 'romantic',
       'family_relationship_quality', 'freetime', 'go_out', 'health',
       'absence_days', 'first_grade', 'second_grade', 'final_grade', 'subject',
       'avg_grade', 'status', 'level'],
      dtype='str')

In [14]:
df["gender"] = df["gender"].map({
    "M": "Male",
    "F": "Female"
})
df["school"] = df["school"].map({
    "GP": "Gabriel Pereira",
    "MS": "Mousinho da Silveira"
})
df["address"] = df["address"].map({
    "U": "Urban",
    "R": "Rural"
})
df["family_size"] = df["family_size"].map({
    "LE3": "Small Family",
    "GT3": "Large Family"
})
df["parents_status"] = df["parents_status"].map({
    "T": "Together",
    "A": "Apart"
})

df.head()

,school,gender,age,address,family_size,parents_status,mother_education,father_education,mother_job,father_job,...,go_out,health,absence_days,first_grade,second_grade,final_grade,subject,avg_grade,status,level
0,Gabriel Pereira,Female,18,Urban,Large Family,Apart,4,4,at_home,teacher,...,4,3,6,5,6,6,math,5.67,Fail,Fail
1,Gabriel Pereira,Female,17,Urban,Large Family,Together,1,1,at_home,other,...,3,3,4,5,5,6,math,5.33,Fail,Fail
2,Gabriel Pereira,Female,15,Urban,Small Family,Together,1,1,at_home,other,...,2,3,10,7,8,10,math,8.33,Pass,Pass
3,Gabriel Pereira,Female,15,Urban,Large Family,Together,4,2,health,services,...,2,5,2,15,14,15,math,14.67,Pass,Excellent
4,Gabriel Pereira,Female,16,Urban,Large Family,Together,3,3,other,other,...,2,5,4,6,10,10,math,8.67,Pass,Pass

In [15]:
education_map = {
    0: "None",
    1: "Primary (up to 4th)",
    2: "5th to 9th grade",
    3: "Secondary education",
    4: "Higher education"
}
traveltime_map = {
    1: "less than 15 min",
    2: "15 to 30 min",
    3: "30 to 60 min",
    4: "greater than 60 min"
}
studytime_map = {
    1: "less than 2 hours",
    2: "2 to 5 hours",
    3: "5 to 10 hours",
    4: "greater than 10 hours"
}
famrel_map = {
    1: "Very bad",
    2: "Bad",
    3: "Average",
    4: "Good",
    5: "Excellent"
}
freetime_map = {
    1: "Very low",
    2: "Low",
    3: "Medium",
    4: "High",
    5: "Very high"
}
goout_map = {
    1: "Very low",
    2: "Low",
    3: "Medium",
    4: "High",
    5: "Very high"
}
health_map = {
    1: "Very bad",
    2: "Bad",
    3: "Average",
    4: "Good",
    5: "Very good"
}

In [16]:
df["mother_education"] = df["mother_education"].map(education_map)
df["father_education"] = df["father_education"].map(education_map)

df["travel_time"] = df["travel_time"].map(traveltime_map)
df["study_time"] = df["study_time"].map(studytime_map)

df["family_relationship_quality"] = df["family_relationship_quality"].map(famrel_map)
df["freetime"] = df["freetime"].map(freetime_map)
df["go_out"] = df["go_out"].map(goout_map)

df["health"] = df["health"].map(health_map)

In [17]:
df.head()

,school,gender,age,address,family_size,parents_status,mother_education,father_education,mother_job,father_job,...,go_out,health,absence_days,first_grade,second_grade,final_grade,subject,avg_grade,status,level
0,Gabriel Pereira,Female,18,Urban,Large Family,Apart,Higher education,Higher education,at_home,teacher,...,High,Average,6,5,6,6,math,5.67,Fail,Fail
1,Gabriel Pereira,Female,17,Urban,Large Family,Together,Primary (up to 4th),Primary (up to 4th),at_home,other,...,Medium,Average,4,5,5,6,math,5.33,Fail,Fail
2,Gabriel Pereira,Female,15,Urban,Small Family,Together,Primary (up to 4th),Primary (up to 4th),at_home,other,...,Low,Average,10,7,8,10,math,8.33,Pass,Pass
3,Gabriel Pereira,Female,15,Urban,Large Family,Together,Higher education,5th to 9th grade,health,services,...,Low,Very good,2,15,14,15,math,14.67,Pass,Excellent
4,Gabriel Pereira,Female,16,Urban,Large Family,Together,Secondary education,Secondary education,other,other,...,Low,Very good,4,6,10,10,math,8.67,Pass,Pass

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   school                       1044 non-null   str
 1   gender                       1044 non-null   str
 2   age                          1044 non-null   int64
 3   address                      1044 non-null   str
 4   family_size                  1044 non-null   str
 5   parents_status               1044 non-null   str
 6   mother_education             1044 non-null   str
 7   father_education             1044 non-null   str
 8   mother_job                   1044 non-null   str
 9   father_job                   1044 non-null   str
 10  reason                       1044 non-null   str
 11  guardian                     1044 non-null   str
 12  travel_time                  1044 non-null   str
 13  study_time                   1044 non-null   str
 14  failures                     1044 non-null   int64
 15  school_support               1044 non-null   str
 16  family_support               1044 non-null   str
 17  paid                         1044 non-null   str
 18  activities                   1044 non-null   str
 19  nursery                      1044 non-null   str
 20  wants_higher_education       1044 non-null   str
 21  internet                     1044 non-null   str
 22  romantic                     1044 non-null   str
 23  family_relationship_quality  1044 non-null   str
 24  freetime                     1044 non-null   str
 25  go_out                       1044 non-null   str
 26  health                       1044 non-null   str
 27  absence_days                 1044 non-null   int64
 28  first_grade                  1044 non-null   int64
 29  second_grade                 1044 non-null   int64
 30  final_grade                  1044 non-null   int64
 31  subject                      1044 non-null   str
 32  avg_grade                    1044 non-null   float64
 33  status                       1044 non-null   str
 34  level                        1044 non-null   str
dtypes: float64(1), int64(6), str(28)
memory usage: 285.6 KB

In [21]:
cols = [
    "school",
    "gender",
    "address",
    "family_size",
    "parents_status",
    "mother_education",
    "father_education",
    "mother_job",
    "father_job",
    "reason",
    "guardian",
    "travel_time",
    "study_time",
    "school_support",
    "family_support",
    "paid",
    "activities",
    "nursery",
    "wants_higher_education",
    "internet",
    "romantic",
    "family_relationship_quality",
    "freetime",
    "go_out",
    "health",
    "status",
    "level",
    "subject"
]

In [22]:
for col in cols:
    df[col] = df[col].astype("category")

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   school                       1044 non-null   category
 1   gender                       1044 non-null   category
 2   age                          1044 non-null   int64
 3   address                      1044 non-null   category
 4   family_size                  1044 non-null   category
 5   parents_status               1044 non-null   category
 6   mother_education             1044 non-null   category
 7   father_education             1044 non-null   category
 8   mother_job                   1044 non-null   category
 9   father_job                   1044 non-null   category
 10  reason                       1044 non-null   category
 11  guardian                     1044 non-null   category
 12  travel_time                  1044 non-null   category
 13  study_time                   1044 non-null   category
 14  failures                     1044 non-null   int64
 15  school_support               1044 non-null   category
 16  family_support               1044 non-null   category
 17  paid                         1044 non-null   category
 18  activities                   1044 non-null   category
 19  nursery                      1044 non-null   category
 20  wants_higher_education       1044 non-null   category
 21  internet                     1044 non-null   category
 22  romantic                     1044 non-null   category
 23  family_relationship_quality  1044 non-null   category
 24  freetime                     1044 non-null   category
 25  go_out                       1044 non-null   category
 26  health                       1044 non-null   category
 27  absence_days                 1044 non-null   int64
 28  first_grade                  1044 non-null   int64
 29  second_grade                 1044 non-null   int64
 30  final_grade                  1044 non-null   int64
 31  subject                      1044 non-null   category
 32  avg_grade                    1044 non-null   float64
 33  status                       1044 non-null   category
 34  level                        1044 non-null   category
dtypes: category(28), float64(1), int64(6)
memory usage: 86.7 KB

In [25]:
df.to_excel("students_cleaned4.xlsx", index=False)